[versions]
min-sdk-version = "24"
target-sdk-version = "34"
gradle-plugin-version = "8.2.1"
kotlin-version = "1.9.22"
kotlin-compiler-extension-version = "1.5.10"
androidx-core-ktx-version = "1.12.0"
compose-bom-version = "2024.04.00"
compose-activity-version = "1.8.2"
compose-nav-version = "2.7.7"
coil-version = "2.5.0"
androidx-unit-version = "1.1.5"
androidx-espresso-version = "3.5.1"
test-junit-jupiter = "5.10.1"
truth = "1.1.5"
androidx-lifecycle-version = "2.7.0"
hilt-version = "2.50"
hilt-navigation-version = "1.2.0"
paparazzi-version = "1.3.1"
retrofit-version = "2.9.0"
okhttp-version = "4.12.0"
gson = "2.10.1"

[libraries]
androidx-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx-version" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle-version" }

compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom-version" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "compose-activity-version" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-graphics = { module = "androidx.compose.ui:ui-graphics" }
compose-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-tooling" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "compose-nav-version" }
compose-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle-version" }

coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-version" }

network-retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit-version" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt-version" }
hilt-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-version" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt-version" }
hilt-android-test = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt-version" }
hilt-android-test-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt-version" }

network-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp-version" }
network-okhttp-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp-version" }

network-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit-version" }
network-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.6.0" }
network-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version = "1.0.0" }

androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-unit-version" }
androidx-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso-version"}
androidx-compose-test = { module = "androidx.compose.ui:ui-test-junit4" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "test-junit-jupiter" }
jupiter = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "test-junit-jupiter" }
jupiter-vintage = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "test-junit-jupiter" }
jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "test-junit-jupiter" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
test-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version = "1.7.3" }
test-okhttp-mockserver = { module = "com.squareup.okhttp3:mockwebserver", version = "4.11.0" }

[bundles]
androidx = ["androidx-ktx", "androidx-lifecycle-runtime"]
compose = ["compose-activity", "compose-ui", "compose-graphics", "compose-preview", "compose-material3", "compose-navigation", "compose-lifecycle-runtime"]
compose-debug = ["compose-ui-tooling", "compose-ui-test-manifest"]
hilt = ["hilt-android", "hilt-navigation"]
retrofit = ["network-okhttp", "network-okhttp-interceptor", "network-retrofit", "network-serialization", "network-serialization-converter"]
ui-testing = ["androidx-junit", "androidx-espresso", "androidx-compose-test", "hilt-android-test"]
unit-testing = ["jupiter", "jupiter-params", "truth", "jupiter-vintage", "test-coroutines", "test-okhttp-mockserver"]

[plugins]
android-application = { id = "com.android.application", version.ref = "gradle-plugin-version" }
android-library = { id = "com.android.library", version.ref = "gradle-plugin-version" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-version" }
parcelable = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin-version" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin-version" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt-version" }
paparazzi = { id = "app.cash.paparazzi", version.ref = "paparazzi-version" }
kotlix-serialization-plugin = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-version" }